-- ### FUNCION DE POLITICA VPD ###

CREATE OR REPLACE FUNCTION es_usuario_estudiante (
  PEVAU IN VARCHAR2,
  ESTUDIANTE IN VARCHAR2
) RETURN VARCHAR2 IS
BEGIN
  -- Check if the user is PEVAU and bypass VPD policy enforcement
  IF SYS_CONTEXT('USERENV', 'SESSION_USER') = 'PEVAU' THEN
    RETURN NULL;
  ELSE
    -- Return the desired VPD policy predicate for other users
    RETURN 'DNI = SUBSTR(SYS_CONTEXT(''USERENV'', ''SESSION_USER''), 2)';
  END IF;
END;
/




-- ### TDE ###

-- EN SYSTEM
alter system set "WALLET_ROOT"='C:\Users\app\alumnos\Oracle_instalacion\wallet' scope=SPFILE;
ALTER SYSTEM SET TDE_CONFIGURATION="KEYSTORE_CONFIGURATION=FILE" scope=both;
select * from v$encryption_wallet;

-- Sqlplus / as syskm
ADMINISTER KEY MANAGEMENT CREATE KEYSTORE IDENTIFIED BY password;
ADMINISTER KEY MANAGEMENT CREATE AUTO_LOGIN KEYSTORE FROM KEYSTORE IDENTIFIED BY password;
ADMINISTER KEY MANAGEMENT SET KEY force keystore identified by password with backup;


SELECT * FROM V$ENCRYPTION_WALLET; -- para ver información del keystore
SELECT * FROM DBA_ENCRYPTED_COLUMNS; -- para ver que está encriptada la columna te telefono


-- ### AUDIT ###

-- AUDIT SOBRE UPDATE, INSERT Y DELETE EN LA TABLA ASISTENCIA PARA TODOS LOS USUARIOS -> no especifica nada en concreto la rubrica
AUDIT UPDATE, INSERT, DELETE ON asistencia BY ACCESS;


-- EN PEVAU;

-- CREACION DE ROLES NECESARIOS PARA LA SEGURIDAD

CREATE ROLE ESTUDIANTE;
CREATE ROLE ADMINISTRADOR;
CREATE ROLE R_SEDE; 
CREATE ROLE R_AULA;
CREATE ROLE V_AULA;
CREATE ROLE PERSONAL_SERVICIO; 

-- Grant a estudiante
GRANT SELECT ON PEVAU.V_ESTUDIANTES TO ESTUDIANTE;
GRANT SELECT ON PEVAU.ASIGNACION_AULA_ESTUDIANTE TO ESTUDIANTE;
GRANT SELECT ON PEVAU.ESTUDIANTES_EXT TO ESTUDIANTE;
-- Grant para administrador
GRANT CREATE TABLE, CREATE VIEW, CREATE MATERIALIZED VIEW, 
CREATE SEQUENCE, CREATE PROCEDURE, CREATE SESSION, CREATE ROLE,
DROP USER, GRANT ANY PRIVILEGE, CREATE USER,GRANT ANY ROLE, AUDIT_ADMIN,
CREATE TRIGGER, CREATE PUBLIC SYNONYM,CREATE ANY DIRECTORY,  ALTER USER TO ADMINISTRADOR;

GRANT ADMINISTRADOR TO PEVAU;


-- Grant para Responsable de sede
GRANT CONNECT, CREATE SESSION TO R_SEDE;
GRANT UPDATE, SELECT, DELETE ON PEVAU.V_ASIGNACION_VIGILANTES TO R_SEDE;
GRANT UPDATE, SELECT, DELETE ON PEVAU.V_RESPONSABLE_SEDE_ASIGNACION_EXAMENES TO R_SEDE;
GRANT UPDATE, SELECT, DELETE ON PEVAU.V_RESPONSABLE_SEDE_ASISTENCIA TO R_SEDE;
GRANT UPDATE, SELECT, DELETE ON PEVAU.V_RESPONSABLE_SEDE_AULAS TO R_SEDE;
GRANT UPDATE, SELECT, DELETE ON PEVAU.V_RESPONSABLE_SEDE_SEDES TO R_SEDE;

-- Grant para Responsable de aula
GRANT CONNECT, CREATE SESSION TO R_AULA;
GRANT SELECT ON PEVAU.V_ASIGNACION_VIGILANTES TO R_AULA;
GRANT UPDATE, SELECT ON PEVAU.V_CONTADOR_ESTUDIANTES_EXAMEN TO R_AULA;

-- Grant para Vigilante de Aula
GRANT CONNECT, CREATE SESSION TO V_AULA;
GRANT SELECT ON PEVAU.V_ASIGNACION_VIGILANTES TO V_AULA;

-- Grant para personal de servicio -> GESTIONAR LOS RESPONSABLES DE SEDE
GRANT CONNECT, CREATE SESSION TO PERSONAL_SERVICIO;
GRANT UPDATE, SELECT, DELETE ON PEVAU.V_RESPONSABLE_SEDE_ASIGNACION_EXAMENES TO PERSONAL_SERVICIO;
GRANT UPDATE, SELECT, DELETE ON PEVAU.V_RESPONSABLE_SEDE_ASISTENCIA TO PERSONAL_SERVICIO;
GRANT UPDATE, SELECT, DELETE ON PEVAU.V_RESPONSABLE_SEDE_AULAS TO PERSONAL_SERVICIO;
GRANT UPDATE, SELECT, DELETE ON PEVAU.V_RESPONSABLE_SEDE_SEDES TO PERSONAL_SERVICIO;
--Consultar asignacion de estudiantes a sedes y aulas
GRANT SELECT ON PEVAU.ASIGNACION_AULA_ESTUDIANTE to PERSONAL_SERVICIO;
--Consultar cantidad de alumnos que han realizado examenes por aula
GRANT SELECT ON PEVAU.V_CONTADOR_ESTUDIANTES_EXAMEN TO PERSONAL_SERVICIO;

-- Vamos a crear ya de paso un usuario de personal de servicio para más adelante poder usarlo 
CREATE USER usuario_personal_servicio IDENTIFIED BY AS012934;
GRANT PERSONAL_SERVICIO TO usuario_personal_servicio;

-- perfil para gestión de contraseñas
CREATE PROFILE perfil_contrasena LIMIT
SESSIONS_PER_USER 3 -- Máximo núm. de sesiones para ese usuario.
CONNECT_TIME UNLIMITED -- Duración máxima de la conexión.
IDLE_TIME 120 -- Minutos de tiempo muerto en una sesión.
FAILED_LOGIN_ATTEMPTS 4 -- nº máximo de intentos para bloquear cuenta.
PASSWORD_LIFE_TIME 90 -- Nº de días de expiración de la password.
PASSWORD_GRACE_TIME 3; -- Periodo de gracia después de los 90 días.