-- system --
-- PRACTICA 1 --


-- Creación de tablespace TS_PEVAU
CREATE TABLESPACE TS_PEVAU DATAFILE 'C:\USERS\APP\ALUMNOS\ORADATA\ORCL\TS_PEVAU.DBF' SIZE 50M;

-- Creación de usuario PEVAU.
CREATE USER PEVAU IDENTIFIED BY pevau_contrasena DEFAULT TABLESPACE TS_PEVAU QUOTA 50M ON TS_PEVAU;

-- Damos los permisos necesarios a PEVAU;
GRANT CREATE TABLE, CREATE VIEW, CREATE MATERIALIZED VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE SESSION, CREATE ROLE, DROP USER, GRANT ANY PRIVILEGE, CREATE USER, AUDIT_ADMIN TO PEVAU;

-- Creación tablespace TS_INDICES
CREATE TABLESPACE TS_INDICES DATAFILE 'C:\USERS\APP\ALUMNOS\ORADATA\ORCL\TS_INDICES.DBF' SIZE 50M;

ALTER USER PEVAU QUOTA 50M ON TS_INDICES;

--Comprobar consultando el diccionario de datos que existen los tablespace TS_PEVAU y TS_INDICES.
SELECT TABLESPACE_NAME FROM DBA_TABLESPACES;

-- Tablespace default
SELECT USERNAME, DEFAULT_TABLESPACE FROM DBA_USERS WHERE USERNAME = 'PEVAU';
--  Comprobar consultando el diccionario de datos los datafiles que tienen asociado TS_PEVAU y TS_INDICES.
SELECT TABLESPACE_NAME, FILE_NAME, BYTES/1024/1024 SIZE_MB FROM DBA_DATA_FILES ;

-- Directorio para la tabla externa
create or replace directory directorio_ext as 'C:\Users\app\alumnos\admin\orcl\dpdump';

grant read, write on directory directorio_ext to PEVAU;

-- Más persmisos para PEVAU
GRANT CREATE TRIGGER TO PEVAU;

GRANT CREATE PUBLIC SYNONYM TO PEVAU;


--############# Para borrar las tablas de PEVAU si es necesario ###########

BEGIN
  FOR cur_rec IN (SELECT table_name FROM all_tables WHERE owner = 'PEVAU') LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || cur_rec.table_name || ' CASCADE CONSTRAINTS';
  END LOOP;
END;
/


-- CREACION DE ROLES NECESARIOS PARA LA SEGURIDAD

CREATE ROLE ESTUDIANTE;
CREATE ROLE ADMINISTRADOR;
CREATE ROLE R_SEDE; 
CREATE ROLE R_AULA;
CREATE ROLE V_AULA;
CREATE ROLE PERSONAL_SERVICIO; 

-- Grant a estudiante
GRANT SELECT ON PEVAU.V_ESTUDIANTES TO ESTUDIANTE;
GRANT SELECT ON PEVAU.ASIGNACION_AULA_ESTUDIANTE TO ESTUDIANTE;

-- Grant para administrador
GRANT CREATE TABLE, CREATE VIEW, CREATE MATERIALIZED VIEW, 
CREATE SEQUENCE, CREATE PROCEDURE, CREATE SESSION, CREATE ROLE,
DROP USER, GRANT ANY PRIVILEGE, CREATE USER, AUDIT_ADMIN,
CREATE TRIGGER, CREATE PUBLIC SYNONYM TO ADMINISTRADOR;

-- Grant para Responsable de sede
GRANT UPDATE, SELECT, DELETE ON PEVAU.V_ASIGNACION_VIGILANTES TO R_SEDE;
GRANT UPDATE, SELECT, DELETE ON PEVAU.V_RESPONSABLE_SEDE_ASIGNACION_EXAMENES TO R_SEDE;
GRANT UPDATE, SELECT, DELETE ON PEVAU.V_RESPONSABLE_SEDE_ASISTENCIA TO R_SEDE;
GRANT UPDATE, SELECT, DELETE ON PEVAU.V_RESPONSABLE_SEDE_AULAS TO R_SEDE;
GRANT UPDATE, SELECT, DELETE ON PEVAU.V_RESPONSABLE_SEDE_SEDES TO R_SEDE;

-- Grant para Responsable de aula
GRANT SELECT ON PEVAU.V_ASIGNACION_VIGILANTES TO R_AULA;
GRANT UPDATE, SELECT ON PEVAU.V_CONTADOR_ESTUDIANTES_EXAMEN TO R_AULA;

-- Grant para Vigilante de Aula
GRANT SELECT ON PEVAU.V_ASIGNACION_VIGILANTES TO V_AULA;

-- Grant para personal de servicio -> GESTIONAR LOS RESPONSABLES DE SEDE
GRANT UPDATE, SELECT, DELETE ON PEVAU.V_RESPONSABLE_SEDE_ASIGNACION_EXAMENES TO PERSONAL_SERVICIO;
GRANT UPDATE, SELECT, DELETE ON PEVAU.V_RESPONSABLE_SEDE_ASISTENCIA TO PERSONAL_SERVICIO;
GRANT UPDATE, SELECT, DELETE ON PEVAU.V_RESPONSABLE_SEDE_AULAS TO PERSONAL_SERVICIO;
GRANT UPDATE, SELECT, DELETE ON PEVAU.V_RESPONSABLE_SEDE_SEDES TO PERSONAL_SERVICIO;
--Consultar asignacion de estudiantes a sedes y aulas
GRANT SELECT ON PEVAU.ASIGNACION_AULA_ESTUDIANTE to PERSONAL_SERVICIO;
--Consultar cantidad de alumnos que han realizado examenes por aula
GRANT SELECT ON PEVAU.V_CONTADOR_ESTUDIANTES_EXAMEN TO PERSONAL_SERVICIO;