-- TODO: PONER USUARIO -> (NOMBRE, ROL, CONTRASEÑA) -> YA SE HAN GENERADO EN LA BASE DE DATOS Y ACCIONES PARA CADA UNO

-- ESTUDIANTE

-- Cosas que debe poder ver
SELECT * FROM PEVAU.V_ESTUDIANTES;
SELECT * FROM PEVAU.ASIGNACION_AULA_ESTUDIANTE;

-- Cosas que no debe poder ver
SELECT * FROM PEVAU.V_OCUPACION;
SELECT * FROM PEVAU.V_ASIGNACION_VIGILANTES;

-- R_AULA -> V86382068I (para demostracion)
-- Cosas que debe poder ver
SELECT * FROM PEVAU.V_CONTADOR_ESTUDIANTES_EXAMEN;
SELECT * FROM PEVAU.V_ASIGNACION_VIGILANTES;
-- Cosas que no debe poder ver
SELECT * FROM PEVAU.V_ESTUDIANTES;

-- R_SEDE -
-- Cosas que debe poder ver
SELECT * FROM PEVAU.V_RESPONSABLE_SEDE_ASIGNACION_EXAMENES;
SELECT * FROM PEVAU.V_ASIGNACION_VIGILANTES;
-- Cosas que no debe poder ver
SELECT * FROM PEVAU.V_ESTUDIANTES;
SELECT * FROM PEVAU.V_CONTADOR_ESTUDIANTES_EXAMEN;

-- V_AULA
-- Cosas que debe poder ver
SELECT * FROM PEVAU.V_ASIGNACION_VIGILANTES;
-- Cosas que no debe poder ver
SELECT * FROM PEVAU.V_RESPONSABLE_SEDE_ASIGNACION_EXAMENES;