-- ######################### USUARIO PARA TODOS LOS ESTUDIANTES



-- ##VISTAS##

-- VISTA ESTUDIANTE PARA VER SU ASIGNACIÓN DE AULA
CREATE OR REPLACE VIEW ASIGNACION_AULA_ESTUDIANTE AS 
SELECT ESTUDIANTE_DNI, MATERIA_CODIGO, EXAMEN_FECHAYHORA, EXAMEN_AULA_CODIGO, EXAMEN_SEDE_CODIGO
FROM ASISTENCIA;

-- VISTA VIGILANTE PARA VER SU ASIGNACIÓN DE AULA

CREATE OR REPLACE VIEW ASIGNACION_AULA_VIGILANTE AS 
SELECT *
FROM VIGILANCIA;

--VISTAS PARA ROLES
CREATE VIEW V_RESPONSABLE_SEDE_AULAS AS
SELECT * FROM AULA;

CREATE VIEW V_RESPONSABLE_SEDE_SEDES AS
SELECT * FROM SEDE;

CREATE VIEW V_RESPONSABLE_SEDE_ASISTENCIA AS
SELECT * FROM ASISTENCIA;

CREATE VIEW V_RESPONSABLE_SEDE_ASIGNACION_EXAMENES AS
SELECT * FROM MATERIA_EXAMEN;
-- 

CREATE OR REPLACE VIEW V_ASIGNACION_VIGILANTES AS
SELECT vi.*, vo.DNI, vo.NOMBRE, vo.APELLIDOS, vo.MATERIA_CODIGO FROM VIGILANCIA vi
JOIN VOCAL vo ON VOCAL_DNI = DNI
WHERE CARGO = 'VIGILANTE' OR CARGO = 'R_AULA';


--RESPONSABLE DE AULA
-- ACTUALIZACIÓN DE ESTUDIANTES EN EL AULA
CREATE OR REPLACE VIEW V_CONTADOR_ESTUDIANTES_EXAMEN AS
SELECT * FROM EXAMEN;






-- creación de usuario para vicerrectorado
CREATE USER VICERRECTORADO IDENTIFIED BY vice_password;



-- AUDIT SOBRE TABLA ASISTENCIA
AUDIT UPDATE, INSERT, DELETE ON asistencia BY ACCESS;



-- TODO: Aplicar VPD que me pasó Pere por discord lo último de todo para no tener
-- problemas al crear los usuarios que me faltan por crear.